repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: ["--autofix", "--indent=4", "--no-sort-keys"]
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
      language_version: python3.7
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        args: ["--py36-plus", "--application-directories=.:src"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.23.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
